### ISSUE TITLE
Needs to depend on sip

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/vitables-feedstock#12]
If you install vitables and run it you get an error

```
Traceback (most recent call last):
  File "/home/aaronmeurer/anaconda3/bin/vitables", line 7, in <module>
    from vitables.start import gui
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/vitables/start.py", line 30, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
```

**Comment by uvemas** [comment]
This should be fixed in version 3.0.2 (PR #14)
